// Generated by LiveScript 1.5.0
(function(){
  var install_extension, out$ = typeof exports != 'undefined' && exports || this;
  document.addEventListener('DOMContentLoaded', function(){
    if (window.location.href.indexOf('http://habitlab.github.io') === 0) {
      return window.location.href = 'https://habitlab.github.io/';
    }
  });
  out$.install_extension = install_extension = function(){
    var url, successCallback;
    if ((typeof chrome != 'undefined' && chrome !== null) && chrome.webstore != null && chrome.webstore.install != null && window.location.protocol === 'https:') {
      return chrome.webstore.install(url = 'https://chrome.google.com/webstore/detail/mogonddkdjlindkbpkagjfkbckgjjmem', successCallback = function(){
        return console.log('extension install finished');
      });
    } else {
      return window.open('https://chrome.google.com/webstore/detail/mogonddkdjlindkbpkagjfkbckgjjmem');
    }
  };
}).call(this);
