#!/bin/bash

if [[ -z `git remote | grep netlify` ]]; then
  git remote add netlify git@github.com:habitlab/habitlab.netlify.com.git
fi
git commit -am "updated website"
git push netlify master
echo "https://habitlab.netlify.com"
